# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bdbbc030d2aae26b755c18865271526c"
name = "lean-equity-app"
handle = "lean-equity-app-2"
application_url = "https://asia-passengers-favourite-mpegs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "minio16.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"

[auth]
redirect_urls = [
  "https://asia-passengers-favourite-mpegs.trycloudflare.com/auth/callback",
  "https://asia-passengers-favourite-mpegs.trycloudflare.com/auth/shopify/callback",
  "https://asia-passengers-favourite-mpegs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
